name: var_30

V: 4096
Cvae: 32
ch: 160
share_quant_resi: 4
patch_nums: [1, 2, 3, 4, 5, 6, 8, 10, 13, 16]
model_depth: 30
shared_aln: false

dataloader: var
image_size: 256 # 256, 512, 1024
batch_size: 32

hflip: false
mid_reso: 1.125

sampling_params:
  cfg: 1.5 # min:1, max:10, step:0.1
  more_smooth: False # [True, False], Set to false during evaluation
  top_k: 900 # min:1, max:1000, step:1
  top_p: 0.96 # min:0.1, max:1, step:0.1
